# Generated by Django 4.0.3 on 2022-03-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_event',
            field=models.TextField(blank=True, null=True),
        ),
    ]
